language: node_js
node_js:
  - stable
before_script:
  - npm install -g gulp bower
  - bower install
script: gulp
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: public/
  on:
    branch: master
